services:
  - type: web
    name: tg-vc-stream-bot
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: OWNER_ID
        sync: false
